# ゲーム設定
FPS = 60
FRAME_TIME = int(1000 / FPS)  # ms

# キャンバスのサイズ
WIDTH = 800
HEIGHT = 600

ENEMY_NUM = 3

PLAYER_SIZE = 30
PLAYER_SPEED = 5
PLAYER_LIVES = 3
PLAYER_COLOR = "blue"

PLAYER_BULLET_SIZE = 10
PLAYER_BULLET_SPEED = 10
PLAYER_BULLET_COLOR = "white"

ENEMY_SIZE = 40
ENEMY_SPEED = 5
ENEMY_LIVES = 1
ENEMY_COLOR = "red"

ENEMY_BULLET_SIZE = 10
ENEMY_BULLET_SPEED = 10
ENEMY_BULLET_COLOR = "yellow"
